baseURL = 'https://smoliicek.cz'
languageCode = 'en-us'
author = 'VÃ­t SmolÃ­k'
copyright = "Â© 2026, smoliicek.cz"
title = 'smoliicek - blog'
theme = "paper"

[params]
  # color style
  color = 'linen'                           # linen, wheat, gray, light

  # header social icons
  twitter = 'smoliiczech'               # twitter.com/YOUR_TWITTER_ID
  github = 'smoliicek'                 # github.com/YOUR_GITHUB_ID
  instagram = 'smoliik.v'           # instagram.com/YOUR_INSTAGRAM_ID
  rss = true                                # show rss icon

  # home page profile
  avatar = 'https://libravatar.org/avatar/4715037e8e298e1cc71d099c5a2c3557?s=80'                 # gravatar email or image url
  name = 'VÃ­t SmolÃ­k'
  bio = 'Linux user, Fedora developer ðŸ‡¨ðŸ‡¿'


  # misc
  disableHLJS = true                        # disable highlight.js
  disablePostNavigation = true              # disable post navigation
  monoDarkIcon = true                       # show monochrome dark mode icon
  math = true                               # enable KaTeX math typesetting globally
  localKatex = false                        # use local KaTeX js/css instead of CDN
